name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ '1.21', '1.22' ]
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go-version }}

    - id: govulncheck
      name: Run govulncheck
      uses: golang/govulncheck-action@v1
      with:
           go-version-input: ${{ matrix.go-version }}
           go-package: ./...

    - name: Test with Go
      run: go test ./... -json > TestResults-${{ matrix.go-version }}.json

    - name: Upload Go test results
      uses: actions/upload-artifact@v4
      with:
        name: Go-results-${{ matrix.go-version }}
        path: TestResults-${{ matrix.go-version }}.json
